# Generated by Django 5.1.4 on 2024-12-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_contact', models.IntegerField()),
                ('stu_pass', models.CharField(max_length=20)),
                ('stu_cpass', models.CharField(max_length=20)),
                ('stu_image', models.FileField(upload_to='images/')),
                ('stu_file', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
